[phases.setup]
nixPkgs = ['python311']

[phases.install]
cmds = ['python3 -m pip install --upgrade pip', 'pip install -r requirements.txt']

[phases.build]
cmds = ['echo "Build complete"']

[start]
cmd = 'gunicorn --bind 0.0.0.0:$PORT league_tracker.app:app --workers 4 --threads 4 --timeout 120'
